[workspace]
members = [
    "P01","P02","P03","P04","P05","P06","P07","P08","P09","P10",
    "P12","P13","P14","P15","P16","P17","P18","P19","P20",
    "P21","P22","P23","P24","P25","P26","P27", "P28"
]

